[
  {
    "id": "sekbaan",
    "name": "石斑",
    "eng": "Grouper",
    "sci": "Epinephelinae",
    "desc": "香港最受歡迎嘅食用魚之一，肉質鮮甜。常見品種包括青斑、芝麻斑、老鼠斑等。棲息於岩石底層，用生蝦或魷魚作餌最有效。",
    "season": "全年",
    "size": "30-100cm",
    "bait": "生蝦、魷魚、魚肉",
    "location": "石灘、礁石區、沉船",
    "difficulty": "中級",
    "image": "🐟",
    "tips": "石斑好鍾意匿埋喺石罅，釣組要貼底，用粗絲腳"
  },
  {
    "id": "wonggeuklaap",
    "name": "黃腳鱲",
    "eng": "Yellowfin Bream",
    "sci": "Acanthopagrus latus",
    "desc": "香港磯釣熱門目標魚，背鰭黃色係特徵。雜食性，力量大，釣上手好有滿足感。",
    "season": "秋冬",
    "size": "20-50cm",
    "bait": "南極蝦、青蟲、麵包",
    "location": "礁石岸邊、碼頭、內灣",
    "difficulty": "初級",
    "image": "🐟",
    "tips": "黃腳鱲食餌好咀刁，要用幼絲同細鉤，南極蝦係最好嘅餌"
  },
  {
    "id": "haklaap",
    "name": "黑鱲",
    "eng": "Black Bream",
    "sci": "Acanthopagrus schlegelii",
    "desc": "同黃腳鱲相似但全身偏黑，同樣係磯釣熱門魚種。冬天最活躍，釣獲量大。",
    "season": "冬季",
    "size": "20-45cm",
    "bait": "南極蝦、青蟲、蝦仁",
    "location": "石岸、防波堤、碼頭",
    "difficulty": "初級",
    "image": "🐟",
    "tips": "黑鱲群體活動，搵到魚群可以連續中魚"
  },
  {
    "id": "hunglau",
    "name": "紅鮋",
    "eng": "Red Gurnard",
    "sci": "Lepidotrigla microptera",
    "desc": "紅色魚身，胸鰭大而華麗。棲息沙泥底，肉質嫩滑。釣到時會發出咕咕聲。",
    "season": "夏秋",
    "size": "15-35cm",
    "bait": "蝦仁、魚肉、青蟲",
    "location": "沙泥海底、內灣",
    "difficulty": "初級",
    "image": "🐟",
    "tips": "紅鮋鍾意沙泥底，用沉底釣法效果最好"
  },
  {
    "id": "nailing",
    "name": "泥鯭",
    "eng": "Rabbitfish",
    "sci": "Siganus oramin",
    "desc": "香港常見魚種，背鰭有毒刺要小心。雜食性，容易釣獲，但肉質一般。",
    "season": "夏季",
    "size": "15-30cm",
    "bait": "麵包、南極蝦、青蟲",
    "location": "碼頭、內灣、石岸",
    "difficulty": "初級",
    "image": "🐟",
    "tips": "泥鯭背鰭有毒，要小心處理。佢哋成日成群出沒"
  },
  {
    "id": "ngadaai",
    "name": "牙帶",
    "eng": "Ribbonfish",
    "sci": "Trichiurus lepturus",
    "desc": "身體扁長似帶，銀白色。牙齒鋒利，要用鋼絲腳。肉質細嫩，清蒸一流。",
    "season": "秋冬",
    "size": "50-120cm",
    "bait": "魚肉、魷魚鬚、生蝦",
    "location": "外海、深水區、夜釣",
    "difficulty": "進階",
    "image": "🐟",
    "tips": "牙帶牙齒好利，一定要用鋼絲腳。夜晚釣獲率更高"
  },
  {
    "id": "wongfayue",
    "name": "黃花魚",
    "eng": "Yellow Croaker",
    "sci": "Larimichthys crocea",
    "desc": "名貴食用魚，金黃色魚身。肉質鮮嫩，價格高昂。近年野生數量減少。",
    "season": "春季",
    "size": "20-50cm",
    "bait": "蝦仁、蟹肉、青蟲",
    "location": "泥泥沙底、河口",
    "difficulty": "進階",
    "image": "🐟",
    "tips": "黃花魚對水質要求高，水清時先有機會釣到"
  },
  {
    "id": "sajun",
    "name": "沙鑽",
    "eng": "Sand Whiting",
    "sci": "Sillago sihama",
    "desc": "沙白色魚身，尖嘴。喺沙灘同沙泥地好常見，釣獲量多，適合一家人玩。",
    "season": "全年",
    "size": "15-30cm",
    "bait": "青蟲、蝦仁、沙蠶",
    "location": "沙灘、沙泥灘、河口",
    "difficulty": "初級",
    "image": "🐟",
    "tips": "沙鑽食餌好脆口，一啄就要抽竿。沙灘釣最好用長投竿"
  },
  {
    "id": "lapyu",
    "name": "立魚",
    "eng": "Sea Bream",
    "sci": "Sparidae",
    "desc": "立魚係統稱，包括黃腳鱲、黑鱲等多種。香港磯釣最主要目標魚群之一。",
    "season": "秋冬季",
    "size": "20-60cm",
    "bait": "南極蝦、青蟲、蟹仔",
    "location": "礁石區、防波堤、碼頭",
    "difficulty": "初級至中級",
    "image": "🐟",
    "tips": "立魚係群體魚類，打誘餌好重要，誘餌粉開得靚先引到魚群"
  },
  {
    "id": "fodim",
    "name": "火點",
    "eng": "Spotty Grouper",
    "sci": "Epinephelus akaara",
    "desc": "身上有紅色斑點，屬於石斑科。肉質極佳，係高級食用魚。棲息於岩礁區。",
    "season": "夏季",
    "size": "20-40cm",
    "bait": "生蝦、蟹仔、魷魚",
    "location": "岩礁區、石排、沉船",
    "difficulty": "中級",
    "image": "🐟",
    "tips": "火點同石斑習性相似，都係匿喺石罅等獵物經過"
  },
  {
    "id": "chingsin",
    "name": "青鱘",
    "eng": "Bluefish",
    "sci": "Pomatomus saltatrix",
    "desc": "青藍色魚身，牙齒鋒利，係凶猛掠食魚。拉力強勁，釣上手好刺激。",
    "season": "夏秋",
    "size": "30-70cm",
    "bait": "魚肉、魷魚、假餌",
    "location": "外海、礁石區、流口",
    "difficulty": "進階",
    "image": "🐟",
    "tips": "青鱘拉力極大，要用粗架生。用假餌拖釣效果好好"
  },
  {
    "id": "chohong",
    "name": "左口",
    "eng": "Flatfish",
    "sci": "Bothidae",
    "desc": "身體扁平成橢圓形，兩隻眼都喺同一邊。棲息沙泥底，肉質鮮嫩。",
    "season": "全年",
    "size": "20-50cm",
    "bait": "蝦仁、青蟲、小魚",
    "location": "沙泥海底、內灣",
    "difficulty": "中級",
    "image": "🐟",
    "tips": "左口鍾意伏喺沙泥底等獵物，沉底釣係最佳方法"
  },
  {
    "id": "singsyu",
    "name": "星鱸",
    "eng": "Spotted Sea Bass",
    "sci": "Lateolabrax maculatus",
    "desc": "身上有黑色斑點，係香港常見嘅食用魚。河口同內灣都有機會釣到。",
    "season": "秋冬",
    "size": "30-80cm",
    "bait": "生蝦、魚肉、假餌",
    "location": "河口、內灣、碼頭",
    "difficulty": "中級",
    "image": "🐟",
    "tips": "星鱸鍾意流水急嘅位置，漲退潮交替時段最好釣"
  },
  {
    "id": "baat",
    "name": "八爪魚",
    "eng": "Octopus",
    "sci": "Octopodidae",
    "desc": "八條觸手，智慧高。棲息岩礁罅隙，用籠或釣組可以捕捉。肉質爽口。",
    "season": "全年",
    "size": "30-100cm",
    "bait": "蟹仔、魷魚、雞肉",
    "location": "岩礁區、石罅、碼頭樁腳",
    "difficulty": "初級",
    "image": "🐙",
    "tips": "八爪魚鍾意匿埋，用八爪魚籠或者釣組貼底拖慢慢收"
  },
  {
    "id": "mangkei",
    "name": "魷魚",
    "eng": "Squid",
    "sci": "Teuthida",
    "desc": "軟體動物，用魷魚餌木釣法最常見。香港夜釣熱門目標，釣獲時會噴墨汁。",
    "season": "夏秋",
    "size": "15-40cm",
    "bait": "餌木、蝦肉",
    "location": "碼頭、燈光下、內灣",
    "difficulty": "初級",
    "image": "🦑",
    "tips": "魷魚趨光，夜晚有燈光嘅碼頭最好釣。餌木要慢慢跳底"
  },
  {
    "id": "siuwan",
    "name": "小環",
    "eng": "Scad",
    "sci": "Decapterus maruadsi",
    "desc": "銀藍色魚身，小型魚，成群出沒。係香港魚排同碼頭常見魚獲。",
    "season": "全年",
    "size": "15-25cm",
    "bait": "南極蝦、麵包、青蟲",
    "location": "魚排、碼頭、內灣",
    "difficulty": "初級",
    "image": "🐟",
    "tips": "小環成群活動，釣到一條就代表附近有一大群"
  },
  {
    "id": "taai",
    "name": "鱲魚",
    "eng": "Porgy",
    "sci": "Pagrus major",
    "desc": "日本料理常見魚種，香港離島水域都有。粉紅色魚身，肉質極佳。",
    "season": "冬季",
    "size": "25-60cm",
    "bait": "南極蝦、蟹肉、青蟲",
    "location": "離島、礁石區、深場",
    "difficulty": "進階",
    "image": "🐟",
    "tips": "真鱲喺深水區活動，要用重磯釣組先釣到"
  },
  {
    "id": "bin",
    "name": "鯆魚",
    "eng": "Ray",
    "sci": "Rajiformes",
    "desc": "身體扁平似魔鬼魚，尾部有毒刺。拉力巨大，釣上手好刺激。屬於底棲魚類。",
    "season": "夏秋",
    "size": "50-150cm",
    "bait": "魚肉、蟹仔、魷魚",
    "location": "沙泥海底、內灣",
    "difficulty": "進階",
    "image": "🐟",
    "tips": "鯆魚拉力好大，但尾部有毒刺要小心。釣到後剪絲放生較好"
  },
  {
    "id": "waanpok",
    "name": "黃鰭鮪",
    "eng": "Yellowfin Tuna",
    "sci": "Thunnus albacares",
    "desc": "遠洋魚種，香港離島外海有機會釣到。肉質極佳，係刺身極品。",
    "season": "夏季",
    "size": "50-200cm",
    "bait": "小魚、魷魚、假餌",
    "location": "外海、離島遠洋",
    "difficulty": "專家",
    "image": "🐟",
    "tips": "黃鰭鮪要用船釣，拖釣係主要方法。拉力極強，要有體力先頂得住"
  }
]
