# Run: python3 fix_fish_sci.py > output.txt
# Then use the output to update the FISH array

FISH_SCI = [
    ("石斑", "Grouper", "30-100cm", "全年", "中級", "Epinephelus marginatus"),
    ("芝麻斑", "Brown-marbled Grouper", "30-80cm", "夏秋", "中級", "Epinephelus fuscoguttatus"),
    ("青斑", "Orange-spotted Grouper", "25-60cm", "夏季", "中級", "Epinephelus coioides"),
    ("東星斑", "Coral Trout", "20-60cm", "夏季", "進階", "Plectropomus leopardus"),
    ("紅斑", "Red Grouper", "20-50cm", "秋冬", "進階", "Epinephelus akaara"),
    ("火點", "Spotty Grouper", "20-40cm", "夏季", "中級", "Epinephelus merra"),
    ("黃腳鱲", "Yellowfin Bream", "20-50cm", "秋冬", "初級", "Acanthopagrus latus"),
    ("黑鱲", "Black Bream", "20-45cm", "冬季", "初級", "Acanthopagrus schlegelii"),
    ("立魚", "Sea Bream", "20-60cm", "秋冬季", "初級", "Pagrus pagrus"),
    ("真鯛", "Red Sea Bream", "25-60cm", "冬季", "進階", "Pagrus major"),
    ("白鱲", "White Snapper", "25-50cm", "秋冬", "中級", "Gymnocranius griseus"),
    ("星鱸", "Spotted Sea Bass", "30-80cm", "秋冬", "中級", "Lateolabrax japonicus"),
    ("盲曹", "Barramundi", "30-100cm", "夏季", "中級", "Lates calcarifer"),
    ("紅鮋", "Red Gurnard", "15-35cm", "夏秋", "初級", "Chelidonichthys lucerna"),
    ("泥鯭", "Rabbitfish", "15-30cm", "夏季", "初級", "Siganus canaliculatus"),
    ("牙帶", "Ribbonfish", "50-120cm", "秋冬", "進階", "Lepidopus caudatus"),
    ("黃花魚", "Yellow Croaker", "20-50cm", "春季", "進階", "Larimichthys crocea"),
    ("沙鑽", "Sand Whiting", "15-30cm", "全年", "初級", "Sillago sihama"),
    ("魷魚", "Squid", "15-40cm", "夏秋", "初級", "Loligo vulgaris"),
    ("鯆魚", "Ray", "50-150cm", "夏秋", "進階", "Dasyatis pastinaca"),
    ("左口", "Flatfish", "20-50cm", "全年", "中級", "Paralichthys olivaceus"),
    ("雞魚", "Javelin Grunter", "20-40cm", "夏秋", "初級", "Pomadasys kaakan"),
    ("細鱗", "Red Morwong", "20-50cm", "冬季", "中級", "Cheilodactylus zonatus"),
    ("青衣", "Green Wrasse", "20-50cm", "夏季", "中級", "Halichoeres hortulanus"),
    ("紅杉", "Red Bigeye", "15-30cm", "全年", "初級", "Priacanthus macracanthus"),
    ("大眼雞", "Bigeye", "15-30cm", "全年", "初級", "Heteropriacanthus cruentatus"),
    ("馬友", "Fourfinger Threadfin", "30-80cm", "夏季", "進階", "Eleutheronema tetradactylum"),
    ("烏頭", "Grey Mullet", "20-60cm", "秋冬", "初級", "Mugil cephalus"),
    ("金古", "Golden Trevally", "20-60cm", "夏季", "中級", "Gnathanodon speciosus"),
    ("池魚", "Horse Mackerel", "15-30cm", "全年", "初級", "Trachurus trachurus"),
    ("梳羅", "Barracuda", "40-120cm", "夏季", "進階", "Sphyraena barracuda"),
    ("三鬚", "Three-lined Grunt", "15-30cm", "全年", "初級", "Plectorhinchus cinctus"),
    ("赤筆", "Red Mullet", "15-30cm", "春季", "初級", "Mullus barbatus"),
    ("剝皮魚", "Filefish", "15-40cm", "冬季", "初級", "Stephanolepis hispidus"),
    ("雞泡魚", "Pufferfish", "10-40cm", "全年", "初級", "Takifugu rubripes"),
    ("鱸魚", "Japanese Sea Bass", "20-70cm", "秋冬", "中級", "Lateolabrax japonicus"),
    ("牛鰍", "Conger Eel", "40-150cm", "全年", "進階", "Conger conger"),
    ("門鱔", "Pike Eel", "50-200cm", "全年", "進階", "Muraenesox cinereus"),
    ("石狗公", "Scorpionfish", "10-25cm", "全年", "初級", "Scorpaena notata"),
    ("黃鰭鮪", "Yellowfin Tuna", "50-200cm", "夏季", "專家", "Thunnus albacares"),
    ("杉斑", "Areolate Grouper", "25-50cm", "夏秋", "中級", "Epinephelus areolatus"),
    ("坑鰜", "Wrasse", "20-50cm", "夏季", "中級", "Cheilinus trilobatus"),
    ("黃衣", "Yellowtail", "30-80cm", "秋冬", "進階", "Seriola lalandi"),
    ("黑鮋", "Black Scorpionfish", "10-25cm", "全年", "初級", "Sebastiscus marmoratus"),
    ("冚畢", "Snubnose Pompano", "20-50cm", "夏季", "中級", "Trachinotus blochii"),
    ("斑𩶘", "Blackspot Tuskfish", "20-45cm", "夏季", "中級", "Choerodon schoenleinii"),
    ("海鱺", "Cobia", "50-150cm", "夏季", "進階", "Rachycentron canadum"),
    ("水針", "Needlefish", "30-80cm", "夏季", "中級", "Tylosurus acus"),
    ("沙鯭", "Lizardfish", "15-30cm", "全年", "初級", "Synodus saurus"),
    ("花利", "Flathead", "25-60cm", "全年", "中級", "Platycephalus indicus"),
    ("金山鯽", "Tilapia", "15-40cm", "全年", "初級", "Oreochromis mossambicus"),
    ("塘虱", "Walking Catfish", "20-50cm", "夏季", "初級", "Clarias batrachus"),
    ("墨魚", "Cuttlefish", "15-40cm", "夏秋", "初級", "Sepia officinalis"),
    ("八爪魚", "Octopus", "20-100cm", "夏秋", "中級", "Octopus vulgaris"),
    ("瀨尿蝦", "Mantis Shrimp", "10-30cm", "全年", "初級", "Oratosquilla oratoria"),
    ("花蟹", "Flower Crab", "15-30cm", "夏秋", "初級", "Portunus pelagicus"),
    ("牛屎(黑鱲)", "Southern Black Bream", "25-50cm", "冬季", "中級", "Acanthopagrus butcheri"),
    ("黑沙(黑鱲)", "Black Sea Bream", "20-45cm", "冬季", "初級", "Acanthopagrus schlegelii"),
    ("白𩶘", "White Bream", "20-40cm", "秋冬", "初級", "Rhabdosargus sarba"),
    ("金絲䱽", "Golden Threadfin", "15-30cm", "全年", "初級", "Nemipterus hexodon"),
    ("花鱸", "Barred Knifejaw", "15-30cm", "夏季", "中級", "Oplegnathus fasciatus"),
    ("石釘", "Rockfish", "15-30cm", "全年", "初級", "Sebastes steindachneri"),
    ("黑毛", "Black Surgeonfish", "20-40cm", "夏季", "中級", "Acanthurus nigrofuscus"),
    ("龍躉", "Giant Grouper", "100-270cm", "夏季", "專家", "Epinephelus lanceolatus"),
    ("皇帝魚", "Spangled Emperor", "30-60cm", "夏季", "中級", "Lethrinus nebulosus"),
    ("紅曹", "Red Snapper", "20-60cm", "夏季", "中級", "Lutjanus erythropterus"),
    ("金鼓", "Golden Rabbitfish", "20-35cm", "夏季", "初級", "Siganus guttatus"),
    ("石蚌", "Diamond Trevally", "30-80cm", "夏季", "中級", "Alectis indica"),
    ("飛魚", "Flying Fish", "15-40cm", "夏季", "中級", "Exocoetus volitans"),
    ("煙管魚", "Flutemouth", "50-150cm", "夏季", "中級", "Fistularia commersonii"),
    ("藍旗𩶘", "Blue-lined Bream", "20-35cm", "秋冬", "初級", "Stenotomus chrysops"),
    ("紅𩶘", "Red Bream", "20-40cm", "秋冬", "初級", "Pagellus erythrinus"),
    ("青龍", "Green Wrasse", "20-50cm", "夏季", "中級", "Halichoeres hortulanus"),
    ("黃祥", "Yellowtail Fusilier", "20-40cm", "夏季", "初級", "Caesio cuning"),
    ("白杉", "White Grouper", "25-60cm", "夏秋", "中級", "Epinephelus akaara"),
    ("花頭梅", "Half-banded Seaperch", "15-30cm", "全年", "初級", "Hypodytes rubicundus"),
    ("白花", "White Croaker", "15-35cm", "冬季", "初級", "Pennahia argentata"),
    ("紅衫", "Golden Thread", "20-40cm", "全年", "初級", "Nemipterus virgatus"),
]

import json
with open('fish_output.txt', 'w') as f:
    f.write("const FISH = [\n")
    for entry in FISH_SCI:
        line = f'  {json.dumps(list(entry), ensure_ascii=False)},'
        f.write(line + "\n")
    f.write("];\n")
    f.write(f"// Total: {len(FISH_SCI)} species\n")
print(f"Generated {len(FISH_SCI)} entries")
